[package]
name = "solana_token_scanner"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
solana-client = "2.3.6"
solana-sdk = "2.3.1"
spl-token-2022 = "9.0.0"
thiserror = "2.0.16"
